### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by DocMolle** [tyler-johnson/Legends#1]
Trying to execute the example code I get an Uncaught ReferenceError: args is not defined at line 657. I am not using it with Node.js. Other functions like "getChampions" work just fine.

**Comment by tyler-johnson** [comment]
Yes, I am in the middle of a refactor. How did you download this code? Via npm or straight from the this repo?

Either way, I'll take a look. I'm sure there's a bunch of little bugs in there right now.

**Comment by DocMolle** [comment]
Oh okay, downloaded it straight from the repo.
I also did a test app with nodejs and got it via npm and it seems to work fine. Nice work btw, I am really liking it!

**Comment by tyler-johnson** [comment]
Thanks! Yea I shouldn't be pushing straight to master. I thought no one was using it right now, but I guess that was a little naive. I'll try to finish this up tonight so the latest API changes are compatible with Legends.
